import React from "react";
import "./globals.css";
import {Inter} from "next/font/google";
import NavbarBootstrap from "@/app/components/navbar";
import FooterBootstrap from "@/app/components/footer";
import Head from "next/head";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: "3050 Wetterdaten-App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
      <Head>
          <link rel="icon" href="/favicon.ico"/>
      </Head>
      <body className={`${inter.className} d-flex flex-column min-vh-100`}>
      <NavbarBootstrap/>
      <main className="flex-grow-1">{children}</main>
      <FooterBootstrap/>
      </body>
      </html>
  );
}
